/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clientedesktop;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.Map;
import java.io.Reader;
import java.net.URLConnection;
import java.net.URLEncoder;
import java.util.LinkedHashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author Andres Garcia
 */
public class ingresarestudiante extends javax.swing.JFrame {

    int posx, posy;
    public ingresarestudiante() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        n = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        d = new javax.swing.JLabel();
        direccion = new javax.swing.JTextField();
        t = new javax.swing.JLabel();
        telefono = new javax.swing.JTextField();
        c = new javax.swing.JLabel();
        cedula = new javax.swing.JTextField();
        j = new javax.swing.JLabel();
        jornada = new javax.swing.JTextField();
        p = new javax.swing.JLabel();
        programa = new javax.swing.JTextField();
        ingresar = new javax.swing.JButton();
        regresar = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setText("INGRESE LOS DATOS DEL ESTUDIANTE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 450, 60));

        n.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        n.setText("Nombre");
        getContentPane().add(n, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 140, -1));
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 250, -1));

        d.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        d.setText("Direccion");
        getContentPane().add(d, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 100, -1));
        getContentPane().add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 250, -1));

        t.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        t.setText("Telefono");
        getContentPane().add(t, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 90, -1));
        getContentPane().add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 250, -1));

        c.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        c.setText("Cedula");
        getContentPane().add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 70, -1));
        getContentPane().add(cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 250, -1));

        j.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        j.setText("Jornada");
        getContentPane().add(j, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, -1, -1));
        getContentPane().add(jornada, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 250, -1));

        p.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        p.setText("Programa");
        getContentPane().add(p, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 140, -1));
        getContentPane().add(programa, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 270, -1));

        ingresar.setBackground(new java.awt.Color(0, 204, 204));
        ingresar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        ingresar.setText("Guardar Datos");
        ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarActionPerformed(evt);
            }
        });
        getContentPane().add(ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 230, 50));

        regresar.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        regresar.setText("ATRAS");
        regresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regresarMouseClicked(evt);
            }
        });
        getContentPane().add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 376, 120, 50));

        fondo.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ingresarest.jpg"))); // NOI18N
        fondo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                fondoMouseDragged(evt);
            }
        });
        fondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fondoMousePressed(evt);
            }
        });
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regresarMouseClicked
        Menu a = new Menu();
       a.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_regresarMouseClicked

    private void fondoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fondoMousePressed
         posx=evt.getX();
         posy=evt.getY();
    }//GEN-LAST:event_fondoMousePressed

    private void fondoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fondoMouseDragged
        int xp=evt.getXOnScreen() -posx;
        int yp= evt.getYOnScreen() - posy;
        this.setLocation(xp, yp);
    }//GEN-LAST:event_fondoMouseDragged

    private void ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarActionPerformed
         try {
            String n = nombre.getText().trim();
            String c = cedula.getText().trim();
            String d = direccion.getText().trim();
            String j = jornada.getText().trim();
            String t = telefono.getText().trim();
            String p = programa.getText().trim();
            
            URL url = new URL("http://localhost/Taller3-master/Vistas/insertviestudiante.php");
            Map<String, Object> params = new LinkedHashMap<>();
 
            params.put("nombre",n);
            params.put("cedula",c);
            params.put("direccion",d);
            params.put("idjor",j);
            params.put("telefono",t);
            params.put("idpro",p);
            
            StringBuilder postData = new StringBuilder();
            for (Map.Entry<String,Object> param : params.entrySet()) {
            if (postData.length() != 0) postData.append('&');
            postData.append(URLEncoder.encode(param.getKey(), "UTF-8"));
            postData.append('=');
            postData.append(URLEncoder.encode(String.valueOf(param.getValue()), "UTF-8"));
            }
            String urlParameters = postData.toString();
            URLConnection conn = url.openConnection();

            conn.setDoOutput(true);

            OutputStreamWriter writer = new OutputStreamWriter(conn.getOutputStream());

            writer.write(urlParameters);
            writer.flush();

            String result = "";
            String line;
            BufferedReader reader = new BufferedReader(new InputStreamReader(conn.getInputStream()));

            while ((line = reader.readLine()) != null) {
            result += line;
            }
            writer.close();
            reader.close();
            System.out.println(result);
            
            

        } catch (Exception e) {
            System.out.println("Exception in NetClientGet:- " + e);
        }
    }//GEN-LAST:event_ingresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ingresarestudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ingresarestudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ingresarestudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ingresarestudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ingresarestudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel c;
    private javax.swing.JTextField cedula;
    private javax.swing.JLabel d;
    private javax.swing.JTextField direccion;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton ingresar;
    private javax.swing.JLabel j;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jornada;
    private javax.swing.JLabel n;
    private javax.swing.JTextField nombre;
    private javax.swing.JLabel p;
    private javax.swing.JTextField programa;
    private javax.swing.JLabel regresar;
    private javax.swing.JLabel t;
    private javax.swing.JTextField telefono;
    // End of variables declaration//GEN-END:variables
}
