/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clientedesktop;

/**
 *
 * @author Andres Garcia
 */
public class Menu extends javax.swing.JFrame {

    int posx, posy;
    public Menu() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        consultaest = new javax.swing.JLabel();
        consultapro = new javax.swing.JLabel();
        insertaest = new javax.swing.JLabel();
        menu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        consultaest.setFont(new java.awt.Font("Arial Black", 3, 10)); // NOI18N
        consultaest.setText("Consulta  estudiante");
        consultaest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consultaest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consultaestMouseClicked(evt);
            }
        });
        getContentPane().add(consultaest, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 150, 60));

        consultapro.setFont(new java.awt.Font("Arial Black", 3, 10)); // NOI18N
        consultapro.setText("Consulta Programa");
        consultapro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        consultapro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consultaproMouseClicked(evt);
            }
        });
        getContentPane().add(consultapro, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 140, 30));

        insertaest.setFont(new java.awt.Font("Arial Black", 3, 10)); // NOI18N
        insertaest.setText("Inserta Estudiante");
        insertaest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                insertaestMouseClicked(evt);
            }
        });
        getContentPane().add(insertaest, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 130, -1));

        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu.jpg"))); // NOI18N
        menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                menuMouseDragged(evt);
            }
        });
        menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuMousePressed(evt);
            }
        });
        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMousePressed
        posx=evt.getX();
        posy=evt.getY();
    }//GEN-LAST:event_menuMousePressed

    private void menuMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseDragged
       int xp=evt.getXOnScreen() -posx;
        int yp= evt.getYOnScreen() - posy;
        this.setLocation(xp, yp);
    }//GEN-LAST:event_menuMouseDragged

    private void consultaestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultaestMouseClicked
        consulestudiante cs = new consulestudiante();
        cs.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_consultaestMouseClicked

    private void consultaproMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultaproMouseClicked
        consulprograma cp = new consulprograma();
        cp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_consultaproMouseClicked

    private void insertaestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insertaestMouseClicked
        
    }//GEN-LAST:event_insertaestMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel consultaest;
    private javax.swing.JLabel consultapro;
    private javax.swing.JLabel insertaest;
    private javax.swing.JLabel menu;
    // End of variables declaration//GEN-END:variables
}
